spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework: DEBUG
