name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Run tests with JaCoCo coverage
      run: ./gradlew jacocoTestReport

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/jacocoTestReport.xml

    - name: Download Code Climate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Prepare Code Climate test reporter
      run: ./cc-test-reporter before-build

    - name: Format coverage report
      run: ./cc-test-reporter format-coverage -t jacoco -o coverage.json build/reports/jacoco/test/jacocoTestReport.xml

    - name: Upload coverage to Code Climate
      run: ./cc-test-reporter upload-coverage -i coverage.json
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
