name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport
      - name: Upload Code Coverage to CodeClimate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make report
          debug: true
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml
          prefix: "${{github.workspace}}"